version: "3.7"

services:
  rx-player:
    build: .
    container_name: rx-player
    ports:
    - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=spring
    restart: unless-stopped