rx-player:
  music-folder: /home/glaze/rx-player/music/
  cover-folder: /home/glaze/rx-player/cover/

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 
            clientSecret: 
            scope:
              - profile
              - email
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB
