# Create a new user
POST localhost:8080/user
Content-Type: application/json

{
  "username": "glaze",
  "password": "dalmatian",
  "email": "glaze@reactive.netty"
}

###

# Get the current user, must be authenticated
GET localhost:8080/user
Authorization: Basic cmVhY3RpdmUtdXNlcjpzZWN1cmU

###

# Finds a user by its id, replace the id with an existing user id
GET localhost:8080/user/61ac128c91df3f1f35730083